/**
 * Unified Feature Flag System
 * Replicates Bun's compile-time feature() logic & runtime GrowthBook/Env checks.
 */

export type FeatureFlag = 
  // Core
  | 'VOICE_MODE' | 'KAIROS' | 'KAIROS_DREAM' | 'KAIROS_BRIEF' | 'KAIROS_CHANNELS' 
  | 'KAIROS_PUSH_NOTIFICATION' | 'KAIROS_GITHUB_WEBHOOKS' | 'CHICAGO_MCP' 
  | 'PROACTIVE' | 'BRIDGE_MODE' | 'DAEMON'
  // Context
  | 'CONTEXT_COLLAPSE' | 'REACTIVE_COMPACT' | 'CACHED_MICROCOMPACT' 
  | 'HISTORY_SNIP' | 'TOKEN_BUDGET' | 'EXTRACT_MEMORIES' | 'TEAMMEM'
  // Tools and Agents
  | 'COORDINATOR_MODE' | 'AGENT_TRIGGERS' | 'AGENT_TRIGGERS_REMOTE' 
  | 'MONITOR_TOOL' | 'WEB_BROWSER_TOOL' | 'TERMINAL_PANEL' | 'WORKFLOW_SCRIPTS' 
  | 'BG_SESSIONS' | 'OVERFLOW_TEST_TOOL' | 'BUDDY' | 'SWARM_TEAMS'
  // UI & Experience
  | 'MESSAGE_ACTIONS' | 'QUICK_SEARCH' | 'AUTO_THEME' | 'STREAMLINED_OUTPUT' | 'CONNECTOR_TEXT'
  // Security & Debugging
  | 'BASH_CLASSIFIER' | 'TRANSCRIPT_CLASSIFIER' | 'NATIVE_CLIENT_ATTESTATION' 
  | 'HARD_FAIL' | 'DUMP_SYSTEM_PROMPT' | 'ABLATION_BASELINE' | 'PROMPT_CACHE_BREAK_DETECTION'
  // Infrastructure
  | 'LODESTONE' | 'DIRECT_CONNECT' | 'SSH_REMOTE' | 'BYOC_ENVIRONMENT_RUNNER' 
  | 'SELF_HOSTED_RUNNER' | 'CCR_REMOTE_SETUP' | 'FORK_SUBAGENT' | 'MCP_SKILLS' 
  | 'EXPERIMENTAL_SKILL_SEARCH' | 'REVIEW_ARTIFACT' | 'BUILDING_CLAUDE_APPS' 
  | 'RUN_SKILL_GENERATOR' | 'ULTRAPLAN' | 'TORCH' | 'TEMPLATES' 
  | 'VERIFICATION_AGENT' | 'COMMIT_ATTRIBUTION' | 'AWAY_SUMMARY' 
  | 'FILE_PERSISTENCE' | 'MEMORY_SHAPE_TELEMETRY' | 'COWORKER_TYPE_TELEMETRY' 
  | 'DOWNLOAD_USER_SETTINGS' | 'UPLOAD_USER_SETTINGS' | 'BREAK_CACHE_COMMAND';

// Defaults matrix for external builds (DCE elimination targets)
const DEFAULTS: Record<FeatureFlag, boolean> = {
  VOICE_MODE: false, KAIROS: false, KAIROS_DREAM: false, KAIROS_BRIEF: false,
  KAIROS_CHANNELS: false, KAIROS_PUSH_NOTIFICATION: false, KAIROS_GITHUB_WEBHOOKS: false,
  CHICAGO_MCP: false, PROACTIVE: false, BRIDGE_MODE: true, DAEMON: false,
  CONTEXT_COLLAPSE: true, REACTIVE_COMPACT: true, CACHED_MICROCOMPACT: true,
  HISTORY_SNIP: true, TOKEN_BUDGET: true, EXTRACT_MEMORIES: true, TEAMMEM: true,
  COORDINATOR_MODE: false, AGENT_TRIGGERS: false, AGENT_TRIGGERS_REMOTE: false,
  MONITOR_TOOL: false, WEB_BROWSER_TOOL: false, TERMINAL_PANEL: true,
  WORKFLOW_SCRIPTS: true, BG_SESSIONS: false, OVERFLOW_TEST_TOOL: false, BUDDY: true, SWARM_TEAMS: false,
  MESSAGE_ACTIONS: true, QUICK_SEARCH: true, AUTO_THEME: true, STREAMLINED_OUTPUT: true, CONNECTOR_TEXT: false,
  BASH_CLASSIFIER: true, TRANSCRIPT_CLASSIFIER: false, NATIVE_CLIENT_ATTESTATION: false,
  HARD_FAIL: false, DUMP_SYSTEM_PROMPT: false, ABLATION_BASELINE: false, PROMPT_CACHE_BREAK_DETECTION: true,
  LODESTONE: true, DIRECT_CONNECT: false, SSH_REMOTE: false, BYOC_ENVIRONMENT_RUNNER: false,
  SELF_HOSTED_RUNNER: false, CCR_REMOTE_SETUP: false, FORK_SUBAGENT: true, MCP_SKILLS: true,
  EXPERIMENTAL_SKILL_SEARCH: false, REVIEW_ARTIFACT: true, BUILDING_CLAUDE_APPS: false,
  RUN_SKILL_GENERATOR: false, ULTRAPLAN: false, TORCH: false, TEMPLATES: false,
  VERIFICATION_AGENT: false, COMMIT_ATTRIBUTION: true, AWAY_SUMMARY: false,
  FILE_PERSISTENCE: true, MEMORY_SHAPE_TELEMETRY: false, COWORKER_TYPE_TELEMETRY: false,
  DOWNLOAD_USER_SETTINGS: true, UPLOAD_USER_SETTINGS: true, BREAK_CACHE_COMMAND: true,
};

export function feature(flag: FeatureFlag): boolean {
  const envKey = `CC_FEATURE_${flag}`;
  if (process.env[envKey] !== undefined) {
    return process.env[envKey] === '1' || process.env[envKey]?.toLowerCase() === 'true';
  }
  return DEFAULTS[flag];
}
